@startuml

entity TypeOfMeal

TypeOfMeal : uuid id
TypeOfMeal : string type
TypeOfMeal : boolean is_active
TypeOfMeal : date create_at

TypeOfMeal : create()
TypeOfMeal : update()
TypeOfMeal : activate()
TypeOfMeal : deactivate()
TypeOfMeal : delete()

entity Mixtures

Mixtures : uuid id
Mixtures : string name
Mixtures : boolean can_freeze
Mixtures : boolean is_active
Mixtures : date create_at

Mixtures : create()
Mixtures : update()
Mixtures : activate()
Mixtures : deactivate()
Mixtures : delete()

entity TodayMenu

TodayMenu : uuid id
TodayMenu : boolean its_frozen
TodayMenu : boolean is_active
TodayMenu : date create_at

TodayMenu : create()
TodayMenu : update()
TodayMenu : activate()
TodayMenu : deactivate()
TodayMenu : delete()

@enduml