name: ci-nutri-menu-app

on: 
  pull_request:
    branches: 
      - main
jobs: 
  status-check: 
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 18
      - run: docker compose run -u root -d -p 3000:3000 app
      - run: docker compose exec -T app bash -c "npm install && npm test" 