name: ci-nutri-menu-app

on:
  pull_request:
    branches:
      - develop
jobs:
  status-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: docker compose run -u root -d -p 3000:3000 app
      - run: docker compose exec -T app bash -c "npm install"
      - run: docker compose exec -T app bash -c "npm test"
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
